/**
 * A typed JSON-RPC client over a long-lived `codex app-server` child.
 *
 * This is the transport `codex exec` could never be. `exec` is one-shot and
 * non-interactive: it cannot stream partial output in a form the bridge can drop,
 * cannot be steered mid-turn, and above all cannot ask the client a question — so
 * permission cards, plan gates and Lines' own tools were all unreachable through
 * it. The app-server is a duplex JSON-RPC peer: it sends notifications *and*
 * makes requests of us.
 *
 * One child per `$CODEX_HOME`, not per session. Threads multiplex over the single
 * connection — every notification carries the `threadId` it belongs to — so a
 * per-session child would be one idle process per open session for no benefit.
 *
 * Lives in the worker's import graph (stdlib + this file) for the reason the
 * worker exists: a bridge hot-reload must not kill a live turn, and the child is
 * owned by whichever process must outlive the bridge.
 *
 * The protocol is marked experimental by the CLI. Everything typed here comes
 * from `shared/codexProtocol`, generated by the installed binary itself — see
 * that directory's README, and `codexAppServer.contract.test.ts` for the canary.
 */
import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import readline from 'node:readline';

/** JSON-RPC id we mint for our own requests. Never collides with the server's own
 *  request ids, which live in a separate space and are echoed back verbatim. */
type RequestId = number;

export interface CodexAppServerOptions {
  /** Discovered `codex` binary. */
  codexPath: string;
  /** `$CODEX_HOME` for this app user — where auth.json and the thread store live. */
  codexHome: string;
  /**
   * Extra environment for the child, on top of the bridge's own.
   *
   * Carries MCP bearer tokens, which is why they are env and not config: codex
   * reads an HTTP server's credential from a variable named by `config.toml`,
   * so the token stays out of the file. Fixed at spawn — a change means a new
   * child, which `ensureServer` handles.
   */
  extraEnv?: Record<string, string>;
  /** A notification from the server (no reply expected). */
  onNotification: (method: string, params: Record<string, unknown>) => void;
  /**
   * A *request* from the server, which must be answered or the turn parks
   * forever. Approvals and tool calls arrive here.
   */
  onServerRequest: (id: unknown, method: string, params: Record<string, unknown>) => void;
  /** The child died. In-flight turns are gone; the next push respawns. */
  onExit: (reason: string) => void;
}

/** What the client reports for an RPC that failed server-side. */
export class CodexRpcError extends Error {
  constructor(
    message: string,
    readonly code: number,
  ) {
    super(message);
    this.name = 'CodexRpcError';
  }
}

export class CodexAppServer {
  private child: ChildProcessWithoutNullStreams;
  private nextId: RequestId = 0;
  private pending = new Map<RequestId, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();
  /** Resolves once `initialize` has answered; every other call awaits it. */
  private ready: Promise<void>;
  private closed = false;

  constructor(private options: CodexAppServerOptions) {
    this.child = spawn(options.codexPath, ['app-server'], {
      // Spreading process.env is required, not cosmetic: without PATH and HOME the
      // child cannot find git or a shell, and CODEX_HOME is what points it at this
      // app user's credentials rather than the user's own ~/.codex.
      env: { ...process.env, ...options.extraEnv, CODEX_HOME: options.codexHome },
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    this.child.stderr.on('data', (d: Buffer) => {
      const text = String(d).trim();
      if (text) console.error('[codex-app-server]', text);
    });
    this.child.on('exit', (code, signal) => this.die(`exited (${signal ?? code})`));
    this.child.on('error', (err) => this.die(err.message));

    readline.createInterface({ input: this.child.stdout }).on('line', (line) => {
      if (!line.trim()) return;
      try {
        this.dispatch(JSON.parse(line) as Record<string, unknown>);
      } catch (err) {
        console.warn('[codex-app-server] unparseable line:', String(err));
      }
    });

    this.ready = this.handshake();
  }

  /**
   * `initialize` then the `initialized` notification, which is what unblocks the
   * server. Deliberately not awaited by the constructor — callers await `ready`
   * through `request`, so a slow handshake delays the first turn rather than the
   * worker's startup.
   */
  private async handshake(): Promise<void> {
    await this.send('initialize', {
      clientInfo: { name: 'lines', title: 'Lines', version: '0.1.0' },
      capabilities: null,
    });
    this.notify('initialized', {});
  }

  private dispatch(msg: Record<string, unknown>) {
    const id = msg.id;
    // A response to something we asked: it carries an id AND a result/error.
    if (id !== undefined && (msg.result !== undefined || msg.error !== undefined)) {
      const waiter = this.pending.get(id as RequestId);
      if (!waiter) return; // already settled, or the child restarted under us
      this.pending.delete(id as RequestId);
      if (msg.error) {
        const error = msg.error as { message?: unknown; code?: unknown };
        waiter.reject(
          new CodexRpcError(String(error.message ?? 'codex rpc failed'), Number(error.code ?? 0)),
        );
      } else {
        waiter.resolve(msg.result);
      }
      return;
    }
    const method = typeof msg.method === 'string' ? msg.method : null;
    if (!method) return;
    const params = (msg.params ?? {}) as Record<string, unknown>;
    // An id on an inbound *method* call means the server wants an answer.
    if (id !== undefined) this.options.onServerRequest(id, method, params);
    else this.options.onNotification(method, params);
  }

  /** Reject everything in flight and tell the owner. Idempotent. */
  private die(reason: string) {
    if (this.closed) return;
    this.closed = true;
    for (const [, waiter] of this.pending) {
      waiter.reject(new Error(`codex app-server ${reason}`));
    }
    this.pending.clear();
    this.options.onExit(reason);
  }

  private write(payload: Record<string, unknown>) {
    if (this.closed) throw new Error('codex app-server is not running');
    this.child.stdin.write(`${JSON.stringify(payload)}\n`);
  }

  /** A request that bypasses the handshake gate — only `initialize` may. */
  private send(method: string, params: Record<string, unknown>): Promise<unknown> {
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      this.pending.set(id, { resolve, reject });
      try {
        this.write({ jsonrpc: '2.0', id, method, params });
      } catch (err) {
        this.pending.delete(id);
        reject(err instanceof Error ? err : new Error(String(err)));
      }
    });
  }

  /** Call a server method and await its result. Waits out the handshake. */
  async request(method: string, params: Record<string, unknown>): Promise<unknown> {
    await this.ready;
    return this.send(method, params);
  }

  notify(method: string, params: Record<string, unknown>): void {
    try {
      this.write({ jsonrpc: '2.0', method, params });
    } catch (err) {
      console.warn('[codex-app-server] notify failed:', String(err));
    }
  }

  /** Answer a request the server made of us. */
  respond(id: unknown, result: unknown): void {
    try {
      this.write({ jsonrpc: '2.0', id: id as never, result });
    } catch (err) {
      console.warn('[codex-app-server] respond failed:', String(err));
    }
  }

  /** Refuse a request the server made of us, with a reason it can surface. */
  respondError(id: unknown, message: string, code = -32000): void {
    try {
      this.write({ jsonrpc: '2.0', id: id as never, error: { code, message } });
    } catch (err) {
      console.warn('[codex-app-server] respondError failed:', String(err));
    }
  }

  get running(): boolean {
    return !this.closed;
  }

  close(): void {
    if (this.closed) return;
    this.die('closed');
    try {
      this.child.kill();
    } catch {
      /* already gone */
    }
  }
}
