/**
 * Codex app-server notifications, normalized into the Claude SDK message shapes
 * the rest of the app already reads.
 *
 * Why normalize rather than add a transcript kind of its own: the bridge's turn
 * machinery — not just the renderer — is keyed to SDK message shapes. The
 * `msg.type === 'result'` settle pass alone drives status, token accounting,
 * spend, the queue flush, the workflow advance, the turn summary and the review
 * diff; `markTurnLive`, `collectTurns`, `scanTurnActivity`, `collectChangedPaths`
 * and the rewind anchor scan all read `assistant`/`user` content blocks. A
 * distinct kind would silently no-op every one of them.
 *
 * Streaming is the reason the `stream_event` shapes below are exact rather than
 * approximate. `isDroppable` on the bridge and the supersede rule in the client
 * store both key off `kind: 'sdk'` + `type: 'stream_event'` — so a delta wearing
 * that envelope is automatically droppable under backpressure and collapsible on
 * the client, while a delta in any other shape would be undroppable and pile up.
 *
 * Every normalized message carries `_engine: 'codex'`, and durable ones carry the
 * raw item in `_codex`, so nothing provider-specific is lost from the JSONL even
 * though the envelope is Claude-shaped.
 *
 * Types come from `./codexProtocol`, generated by the installed CLI. This module
 * is deliberately pure: no I/O, no state, so the whole mapping is testable from a
 * fixture stream.
 */
import type { ThreadItem } from './codexProtocol/v2/ThreadItem.ts';
import type { TokenUsageBreakdown } from './codexProtocol/v2/TokenUsageBreakdown.ts';

export type { ThreadItem, TokenUsageBreakdown };

/** A Claude-SDK-shaped message, as the bridge and the renderer consume it. */
export type SdkShapedMessage = Record<string, unknown> & { type: string };

export interface CodexNormalizeDeps {
  /** Mints the `uuid` an assistant message needs (the rewind anchor scan reads it). */
  newId: () => string;
  /** The Lines model id this turn ran on, echoed into the message envelope. */
  model: string;
  /**
   * The most recent `thread/tokenUsage/updated` for this thread.
   *
   * Usage arrives on its own notification *before* `turn/completed`, so the
   * caller tracks it and hands it back here — which keeps this module pure while
   * still letting the settling `result` carry real numbers.
   */
  lastUsage?: TokenUsageBreakdown | null;
}

export interface CodexNormalized {
  /** Messages to feed through the ordinary SDK event path, in order. */
  messages: SdkShapedMessage[];
  /** Thread id captured from `thread/started`; the resume pointer. */
  threadId?: string;
  /** A fatal failure whose text must reach `failTurn` verbatim. */
  failure?: string;
  /** Token usage seen on this notification, for the caller to remember. */
  usage?: TokenUsageBreakdown;
  /** The turn ended under a Stop rather than finishing or failing. */
  interrupted?: boolean;
}

/**
 * Envelope the worker forwards one app-server notification in. It rides the same
 * event channel as the SDK messages, so it needs a `type` no SDK message uses.
 */
export const CODEX_NOTIFICATION = 'codexNotification';

export interface CodexNotificationEnvelope {
  type: typeof CODEX_NOTIFICATION;
  method: string;
  params: Record<string, unknown>;
}

/** Narrows a worker event to a codex notification before the bridge normalizes it. */
export function isCodexNotification(value: unknown): value is CodexNotificationEnvelope {
  if (typeof value !== 'object' || value === null) return false;
  const msg = value as Record<string, unknown>;
  return (
    msg.type === CODEX_NOTIFICATION &&
    typeof msg.method === 'string' &&
    typeof msg.params === 'object' &&
    msg.params !== null
  );
}

const NOTHING: CodexNormalized = { messages: [] };

/**
 * `tool_use_id` for one codex item. Derived from the item id rather than minted,
 * so the `tool_use` and the `tool_result` emitted from the *same* item pair up in
 * the renderer with no shared state.
 */
export function codexToolUseId(itemId: string): string {
  return `codex_${itemId}`;
}

/** Tool name an item renders under. `ApplyPatch` is deliberately not one of the
 *  Claude edit tools: codex reports no before/after, so pairing it into a diff
 *  card would promise a diff that does not exist. */
function toolNameFor(item: ThreadItem): string {
  switch (item.type) {
    case 'commandExecution':
      return 'Bash';
    case 'fileChange':
      return 'ApplyPatch';
    case 'mcpToolCall':
      return `mcp__${item.server}__${item.tool}`;
    case 'webSearch':
      return 'WebSearch';
    case 'dynamicToolCall':
      return item.tool;
    default:
      return item.type;
  }
}

function toolInputFor(item: ThreadItem): Record<string, unknown> {
  switch (item.type) {
    case 'commandExecution':
      return { command: item.command };
    case 'fileChange':
      return { changes: item.changes };
    case 'mcpToolCall':
      return { server: item.server, tool: item.tool, arguments: item.arguments };
    case 'webSearch':
      return { query: (item as { query?: string }).query ?? '' };
    case 'dynamicToolCall':
      return { arguments: item.arguments };
    default:
      return {};
  }
}

/** Text the tool card shows as the call's output, and whether it failed. */
function toolResultFor(item: ThreadItem): { text: string; isError: boolean } {
  switch (item.type) {
    case 'commandExecution': {
      const failed = item.status === 'failed' || (item.exitCode != null && item.exitCode !== 0);
      const code = item.exitCode != null ? `\nExit code: ${item.exitCode}` : '';
      return { text: `${item.aggregatedOutput ?? ''}${code}`, isError: failed };
    }
    case 'fileChange':
      return {
        text: item.changes.map((c) => `${c.kind} ${c.path}`).join('\n'),
        isError: item.status === 'failed',
      };
    case 'mcpToolCall': {
      if (item.error) return { text: String(item.error.message ?? 'failed'), isError: true };
      return { text: JSON.stringify(item.result ?? null), isError: item.status === 'failed' };
    }
    case 'dynamicToolCall':
      return {
        text: JSON.stringify(item.contentItems ?? null),
        isError: item.success === false,
      };
    default:
      return { text: '', isError: false };
  }
}

function assistantMessage(
  deps: CodexNormalizeDeps,
  content: Record<string, unknown>[],
  raw: unknown,
): SdkShapedMessage {
  return {
    type: 'assistant',
    uuid: deps.newId(),
    parent_tool_use_id: null,
    message: {
      id: deps.newId(),
      type: 'message',
      role: 'assistant',
      model: deps.model,
      content,
      stop_reason: null,
      stop_sequence: null,
    },
    _engine: 'codex',
    _codex: raw,
  };
}

function toolResultMessage(
  deps: CodexNormalizeDeps,
  toolUseId: string,
  result: { text: string; isError: boolean },
  raw: unknown,
): SdkShapedMessage {
  return {
    type: 'user',
    uuid: deps.newId(),
    parent_tool_use_id: null,
    message: {
      role: 'user',
      content: [
        {
          type: 'tool_result',
          tool_use_id: toolUseId,
          content: result.text,
          ...(result.isError ? { is_error: true } : {}),
        },
      ],
    },
    _engine: 'codex',
    _codex: raw,
  };
}

/** A `stream_event`-shaped message. The envelope is what makes it droppable. */
function streamEvent(event: Record<string, unknown>): SdkShapedMessage {
  return { type: 'stream_event', parent_tool_use_id: null, event, _engine: 'codex' };
}

/** The content-block kind a starting item streams as, or null when it streams
 *  nothing the live row can show. */
function startingBlock(item: ThreadItem): Record<string, unknown> | null {
  switch (item.type) {
    case 'agentMessage':
      return { type: 'text' };
    case 'reasoning':
      return { type: 'thinking' };
    case 'commandExecution':
    case 'fileChange':
    case 'mcpToolCall':
    case 'webSearch':
    case 'dynamicToolCall':
      return { type: 'tool_use', name: toolNameFor(item) };
    default:
      return null;
  }
}

/** The durable messages one completed item becomes. */
function completedItem(item: ThreadItem, deps: CodexNormalizeDeps): SdkShapedMessage[] {
  switch (item.type) {
    // Lines wrote its own 'user' transcript event when the prompt was sent;
    // echoing codex's copy back would double every prompt.
    case 'userMessage':
      return [];
    case 'agentMessage':
      return item.text ? [assistantMessage(deps, [{ type: 'text', text: item.text }], item)] : [];
    case 'plan':
      return item.text ? [assistantMessage(deps, [{ type: 'text', text: item.text }], item)] : [];
    case 'reasoning': {
      // `summary` is the readable form; `content` is the raw trace, which the CLI
      // itself only shows on request. Prefer the summary, fall back to content.
      const text = [...(item.summary ?? []), ...(item.summary?.length ? [] : (item.content ?? []))]
        .filter(Boolean)
        .join('\n\n');
      return text
        ? [assistantMessage(deps, [{ type: 'thinking', thinking: text, signature: '' }], item)]
        : [];
    }
    case 'commandExecution':
    case 'fileChange':
    case 'mcpToolCall':
    case 'webSearch':
    case 'dynamicToolCall': {
      const toolUseId = codexToolUseId(item.id);
      return [
        assistantMessage(
          deps,
          [{ type: 'tool_use', id: toolUseId, name: toolNameFor(item), input: toolInputFor(item) }],
          item,
        ),
        toolResultMessage(deps, toolUseId, toolResultFor(item), item),
      ];
    }
    // Everything else (review-mode markers, sub-agent activity, compaction
    // markers, image views) has no Claude-shaped home and no card to render into.
    // Dropped rather than invented: a made-up tool row would read as work the
    // agent did not do.
    default:
      return [];
  }
}

/** The token counts a settling `result` carries, in the SDK's own field names. */
function resultUsage(usage: TokenUsageBreakdown | null | undefined) {
  return {
    input_tokens: usage?.inputTokens ?? 0,
    // Reasoning tokens are billed output; folding them in is what keeps the
    // session's spend from under-reporting.
    output_tokens: (usage?.outputTokens ?? 0) + (usage?.reasoningOutputTokens ?? 0),
    cache_read_input_tokens: usage?.cachedInputTokens ?? 0,
    cache_creation_input_tokens: usage?.cacheWriteInputTokens ?? 0,
  };
}

/**
 * One app-server notification as SDK-shaped messages.
 *
 * Unknown methods map to nothing on purpose: this protocol is experimental and
 * grows, and an unrecognised notification must be inert rather than an error.
 */
export function normalizeCodexNotification(
  method: string,
  params: Record<string, unknown>,
  deps: CodexNormalizeDeps,
): CodexNormalized {
  switch (method) {
    case 'thread/started': {
      const thread = params.thread as { id?: unknown } | undefined;
      return typeof thread?.id === 'string' ? { messages: [], threadId: thread.id } : NOTHING;
    }
    case 'turn/started':
      // Resets the client's streaming tail, exactly as a Claude turn's does.
      return { messages: [streamEvent({ type: 'message_start' })] };
    case 'item/started': {
      const block = startingBlock(params.item as ThreadItem);
      return block
        ? { messages: [streamEvent({ type: 'content_block_start', content_block: block })] }
        : NOTHING;
    }
    case 'item/agentMessage/delta': {
      const delta = params.delta;
      return typeof delta === 'string' && delta
        ? {
            messages: [
              streamEvent({
                type: 'content_block_delta',
                delta: { type: 'text_delta', text: delta },
              }),
            ],
          }
        : NOTHING;
    }
    case 'item/reasoning/textDelta':
    case 'item/reasoning/summaryTextDelta': {
      const delta = params.delta;
      return typeof delta === 'string' && delta
        ? {
            messages: [
              streamEvent({
                type: 'content_block_delta',
                delta: { type: 'thinking_delta', thinking: delta },
              }),
            ],
          }
        : NOTHING;
    }
    case 'item/completed':
      return { messages: completedItem(params.item as ThreadItem, deps) };
    case 'thread/tokenUsage/updated': {
      const usage = (params.tokenUsage as { last?: TokenUsageBreakdown } | undefined)?.last;
      return usage ? { messages: [], usage } : NOTHING;
    }
    case 'turn/completed': {
      const turn = params.turn as
        | { status?: string; error?: { message?: unknown } | null; durationMs?: number | null }
        | undefined;
      const status = turn?.status;
      // A failure is a `turn/completed` with a status, not a notification of its
      // own — so the failure path is decided here rather than by method name.
      if (status === 'failed') {
        return {
          messages: [],
          failure: String(turn?.error?.message ?? 'The turn failed.'),
        };
      }
      return {
        messages: [
          {
            type: 'result',
            subtype: 'success',
            is_error: false,
            usage: resultUsage(deps.lastUsage),
            // No `total_cost_usd`: codex reports tokens, never a price.
            ...(typeof turn?.durationMs === 'number' ? { duration_ms: turn.durationMs } : {}),
            _engine: 'codex',
            _codex: turn,
          },
        ],
        ...(status === 'interrupted' ? { interrupted: true } : {}),
      };
    }
    default:
      return NOTHING;
  }
}
